# Generated by Django 3.2.7 on 2021-11-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshopper', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_method',
            field=models.CharField(blank=True, choices=[('fb', 'Facebook'), ('Twitter', 'Twitter'), ('Google', 'Google')], max_length=20, null=True),
        ),
    ]
