# Generated by Django 3.2.7 on 2021-11-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshopper', '0003_alter_user_registration_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_order',
            name='shipping_method',
            field=models.IntegerField(null=True),
        ),
    ]
