# Generated by Django 3.2.7 on 2021-11-28 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eshopper', '0004_alter_user_order_shipping_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
