# Generated by Django 3.2.7 on 2021-11-28 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_parent_id'),
        ('cart', '0001_initial'),
        ('Eshopper', '0005_alter_user_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_order',
            name='coupon_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.coupon'),
        ),
        migrations.AlterField(
            model_name='user_order',
            name='payment_gateway_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.payment_gateway'),
        ),
        migrations.AlterField(
            model_name='user_order',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterField(
            model_name='user_order',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
