# Generated by Django 3.2.7 on 2021-11-30 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('Eshopper', '0009_auto_20211130_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_order',
            name='coupon_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.coupon'),
        ),
        migrations.AlterField(
            model_name='user_order',
            name='payment_gateway_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.payment_gateway'),
        ),
    ]
