# Generated by Django 3.2.7 on 2021-12-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshopper', '0010_auto_20211130_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_order',
            name='shipping_city',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='user_order',
            name='shipping_country',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='user_order',
            name='shipping_state',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='user_order',
            name='shipping_zipcode',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
