# Generated by Django 3.2.7 on 2021-12-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshopper', '0011_auto_20211202_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_order',
            name='shipping_address_1',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
