# Generated by Django 3.2.7 on 2021-12-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshopper', '0012_alter_user_order_shipping_address_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_order',
            name='shipping_charges',
            field=models.FloatField(default=0),
        ),
    ]
