# Generated by Django 3.2.7 on 2021-12-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshopper', '0013_alter_user_order_shipping_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fb_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
