# Generated by Django 3.2.7 on 2021-12-09 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eshopper', '0017_alter_orderhistory_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eshopper.orderitem'),
        ),
    ]
