# Generated by Django 3.2.7 on 2021-11-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Pro_Image',
            field=models.ImageField(blank=True, null=True, upload_to='my_images'),
        ),
    ]
