# Generated by Django 3.2.7 on 2021-12-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_pro_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='special_price_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='special_price_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
