# Generated by Django 3.2.7 on 2021-12-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20211202_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='special_price_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='special_price_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
