# Generated by Django 3.2.7 on 2021-12-07 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerHomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modify_date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='my_images')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive')], max_length=15)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bannerhomepage_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('modify_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bannerhomepage_modify_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
