# Generated by Django 3.2.7 on 2021-12-14 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),
        ('custom_admin', '0003_auto_20211214_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cms',
            name='content',
        ),
        migrations.RemoveField(
            model_name='cms',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cms',
            name='title',
        ),
        migrations.AddField(
            model_name='cms',
            name='flatpage_ptr',
            field=models.OneToOneField(auto_created=True, default=2, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flatpages.flatpage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cms',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cms',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cms',
            name='meta_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
