# Generated by Django 3.2.7 on 2021-12-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0004_auto_20211214_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='contact_no',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='note_admin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
